### ISSUE TITLE
Extend RunCommand to allow env vars to be set

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/cma-vmware#34]
There are now two implementations of run command. These should be combined so that both benefit from timeouts, shared logging formats, etc.

Shared RunCommand() implementation:

https://github.com/samsung-cnct/cma-vmware/blob/65229a467815fe3a5106859265d031e7f6ff2d86/internal/apiserver/clusterapi.go#L650

Reimplementation without timeout:

https://github.com/samsung-cnct/cma-vmware/blob/65229a467815fe3a5106859265d031e7f6ff2d86/internal/apiserver/clusterapi.go#L434

**Comment by oneilcin** [comment]
I found I don't need the Env option now, and can use the existing RunCommand.  We don't need this at the moment.

**Comment by davidewatson** [comment]
Closing since this was not needed and we now have cma-ssh.
